const prefix = '@@GAME';
const LOAD_BIRD_CATEGORIES = `${prefix}_LOAD_BIRD_CATEGORIES`;
const LOAD_BIRDS_FROM_CATEGORY = `${prefix}_LOAD_BIRDS_FROM_CATEGORY`;
const SELECT_RANDOM_BIRD = `${prefix}_SELECT_RANDOM_BIRD`;
const ON_SELECT_ANSWER = `${prefix}_ON_SELECT_ANSWER`;
const ON_NEXT_LEVEL = `${prefix}_ON_NEXT_LEVEL`;
const ON_PLAY_AGAIN = `${prefix}_ON_PLAY_AGAIN`;

export {
  LOAD_BIRD_CATEGORIES,
  LOAD_BIRDS_FROM_CATEGORY,
  SELECT_RANDOM_BIRD,
  ON_SELECT_ANSWER,
  ON_NEXT_LEVEL,
  ON_PLAY_AGAIN,
};
