const LOAD_BIRD_CATEGORIES = 'LOAD_BIRD_CATEGORIES';
const LOAD_BIRDS_FROM_CATEGORY = 'LOAD_BIRDS_FROM_CATEGORY';
const SELECT_RANDOM_BIRD = 'SELECT_RANDOM_BIRD';
const ON_SELECT_ANSWER = 'ON_SELECT_ANSWER';
const ON_NEXT_LEVEL = 'ON_NEXT_LEVEL';
const ON_PLAY_AGAIN = 'ON_PLAY_AGAIN';

export {
  LOAD_BIRD_CATEGORIES,
  LOAD_BIRDS_FROM_CATEGORY,
  SELECT_RANDOM_BIRD,
  ON_SELECT_ANSWER,
  ON_NEXT_LEVEL,
  ON_PLAY_AGAIN,
};
