const prefix = '@@BIRD_CATALOG';
const LOAD_ALL_BIRDS = `${prefix}_LOAD_ALL_BIRDS`;
const LOAD_SELECTED_BIRD_FROM_CATALOG = `${prefix}_LOAD_SELECTED_BIRD_FROM_CATALOG`;

export { LOAD_ALL_BIRDS, LOAD_SELECTED_BIRD_FROM_CATALOG };
