const prefix = '@@BIRD_CATALOG';
const LOAD_ALL_BIRDS = `${prefix}_LOAD_ALL_BIRDS`;
const SELECT_BIRD_FROM_CATALOG = `${prefix}_SELECT_BIRD_FROM_CATALOG`;

export { LOAD_ALL_BIRDS, SELECT_BIRD_FROM_CATALOG };
